### ISSUE TITLE
ckati failed with: exit status 1

### ISSUE THREAD

**Issue by aohanhongzhi** [PixysOS-Devices/device_xiaomi_onclite#1]
![Screenshot from 2022-05-07 09-17-45](https://user-images.githubusercontent.com/37319319/167232934-12e2c451-6594-42ad-bb45-83e18592b6f9.png)

**Comment by aohanhongzhi** [comment]
I build it successfully.but after flash , the phone doesn't enter to system.

**Comment by AbhinandAK350** [comment]
Dt is fine.
